### ISSUE TITLE
"Couldn't open file" when started recording & progress isn't reported correctly.

### ISSUE THREAD

**Issue by sunshinejr** [sindresorhus/Gifski#186]
This is my workflow:
1. Run simulator recording
```
xcrun simctl io booted recordVideo "$1"
```
1. Stop & open the file with Gifski
1. Tap convert

What happens is that most of the time I tap convert it says "Couldn't open file", I have to wait (or tap on buttons, not sure which one works) and it converts eventually. Also when it finally starts converting, the progress reported isn't entirely accurate since it finishes at about 50%.

There is no particular video that triggers that as it is consistently reproducible. I'm thinking if this has something to do with APFS?

**Comment by sindresorhus** [comment]
> Also when it finally starts converting, the progress reported isn't entirely accurate since it finishes at about 50%.

This is caused by #187.

**Comment by sindresorhus** [comment]
Fixture that reproduces the issue: [simulator-recording.mp4.zip](https://github.com/sindresorhus/Gifski/files/4435996/simulator-recording.mp4.zip)

I have looked into the problem and it turns out the problem is that the recording contains blank frames at the start. If you open the video in QuickTime and go to the start, you'll see that it's blank (black) for some milliseconds. This is IMHO a bug in `simctl`, but we should still work around it as there could be valid videos with blank frames at the start too.
