### ISSUE TITLE
Share extension

### ISSUE THREAD

**Issue by sindresorhus** [sindresorhus/Gifski#81]
[<img alt="Issuehunt badges" src="https://img.shields.io/badge/IssueHunt-%24100%20Funded-%2300A156.svg" />](https://issuehunt.io/r/sindresorhus/gifski-app/issues/81)

I think it would be useful to create a [Share extension](https://developer.apple.com/design/human-interface-guidelines/macos/extensions/share-extensions/) for Gifski. That way, any video/screen recording app with a system "Share" button would be able to send a video to Gifski.

This would be especially useful for the built-in macOS screen recording feature. When you're done recording there, you get a thumbnail at the bottom-right of the screen. If you click it, a preview window opens, and in the toolbar, there's a "Share" button. So the user could then quickly send it to Gifski after recording without even having to save the video file.

Thoughts?

---

<details>
<summary>
<b>IssueHunt Summary</b>
</summary>

### Backers (Total: $100.00)

- [<img src='https://avatars3.githubusercontent.com/u/44827199?v=4' alt='issuehunt' width=24 height=24> issuehunt](https://issuehunt.io/u/issuehunt) ($100.00)
### Submitted pull Requests
- [#156 Create Share extension](https://issuehunt.io/r/sindresorhus/gifski-app/pull/156)
---

### Tips

- Checkout the [Issuehunt explorer](https://issuehunt.io/r/sindresorhus/gifski-app/) to discover more funded issues.
- Need some help from other developers? [Add your repositories](https://issuehunt.io/r/new) on IssueHunt to raise funds.
---
IssueHunt has been backed by the following sponsors. [Become a sponsor](https://issuehunt.io/membership/members)
</details>

**Comment by sunshinejr** [comment]
I'd love to see this one as well.

**Comment by AnderGoig** [comment]
I've been doing some testing and haven't found a way to open the host app from the Share extension. There is an `open(:url)` [method](https://developer.apple.com/documentation/foundation/nsextensioncontext/1416791-open) but I couldn't make it work with this extension.

Was that the idea, or am I missing something?

**Comment by sunshinejr** [comment]
@AnderGoig we had a similar problem on iOS few years back. From what I remember, you had to climb the responder chain and stop once you got the host app. Not sure if it's gonna work on macOS, but worth a try.

**Comment by Ybrin** [comment]
I can do this if it is still relevant.

**Comment by sunshinejr** [comment]
@Ybrin yes I think it's still relevant so go ahead 👍

**Comment by Ybrin** [comment]
Ok I got this but we need to discuss how exactly the process should behave.

Share extensions normally have a custom UI and don't really open the master app to process the shared item. There is a workaround I'm currently using in order to open Gifski and close the share extension immediately but it's more a hack...

How do you want to do this? Should I stick with the hack and just open Gifski with a url and let it handle the rest or should we handle this differently?

If we're going ahead with the "hack" I need to find a way to pass the video file over to Gifski. The url becomes invalid once the share extension is closed as it's not a url to the original location but rather to a tmp folder containing a symlink or something. I guess I will have to copy it over to somewhere and pass this url to Gifski or something. If you have any ideas or know what's happening here let me know please.

@sindresorhus @sunshinejr

**Comment by sunshinejr** [comment]
@Ybrin UserDefaults with custom suite name? I think this should work between extension & an app. If the hack is working properly, I wouldn't mind it (but leaving the decision to Sindre).

**Comment by Ybrin** [comment]
The hack is opening one of the url schemes assigned to Gifski and passing
the video uri as a parameter. I don’t like it but I don’t see any other way
to open the original app from an extension.

**Comment by Ybrin** [comment]
The thing is, I have to open it with a webview in the extension. So the
Extension view is actually an empty webview which stays open until Gifski
starts launching.

**Comment by sindresorhus** [comment]
@Ybrin Could you use App Groups to copy the video into a shared container that Gifski can access?

Another possibility it to just pass raw bytes into Gifski from the extension.

**Comment by Ybrin** [comment]
@sindresorhus I‘ll have a look into app groups and let you know.
